### ISSUE TITLE
Sync fails while trying to unwind

### ISSUE THREAD

**Issue by crypto-dev-ext** [akula-bft/akula#149] opened 2022-01-31 18:57 UTC
Hi, I'm trying to give akula a try, but I am unable to complete a sync due to the error:

Error: Not enough data to fill buffer
nohup: ignoring input

This causes akula to exit/crash

I get the same behaviour every time i restart. I have an erigon node which is running and I am giving the data dir in the cmd line when starting. The initial sync completed, leading to the unwind operation and now it's stuck there. 

Logs below on the latest restart that was done. Let me know if there's any info I can provide

Thanks!

ESC[2m2022-01-25T13:54:05.131317ZESC[0m ESC[32m INFOESC[0m Starting Akula (akula/v0.1.0-master-b895356-2022-01-14/x86_64-unknown-linux-gnu/rustc1.57.0-nightly)
ESC[2m2022-01-25T13:54:05.308048ZESC[0m ESC[32m INFOESC[0m Running staged sync
ESC[2m2022-01-25T13:54:05.308616ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m 1/10 ConvertHeaders ESC[1m}ESC[0mESC[2m:ESC[0m RUNNING from 14069241
ESC[2m2022-01-25T13:54:05.310050ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m 1/10 ConvertHeaders ESC[1m}ESC[0mESC[2m:ESC[0m Unwind requested ESC[3mtoESC[0mESC[2m=
ESC[0m14069240
ESC[2m2022-01-25T13:54:05.310194ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 10/10 Finish ESC[1m}ESC[0mESC[2m:ESC[0m UNWINDING from 14069241
ESC[2m2022-01-25T13:54:07.453515ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 10/10 Finish ESC[1m}ESC[0mESC[2m:ESC[0m DONE @ 14069240
ESC[2m2022-01-25T13:54:07.453587ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 9/10 CallTraces ESC[1m}ESC[0mESC[2m:ESC[0m UNWINDING from 14069241
ESC[2m2022-01-25T13:54:24.239840ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 9/10 CallTraces ESC[1m}ESC[0mESC[2m:ESC[0m DONE @ 14069240
ESC[2m2022-01-25T13:54:24.239885ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 8/10 Interhashes ESC[1m}ESC[0mESC[2m:ESC[0m UNWINDING from 14069241
ESC[2m2022-01-25T14:27:28.379481ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 8/10 Interhashes ESC[1m}ESC[0mESC[2m:ESC[0m DONE @ 0
ESC[2m2022-01-25T14:27:28.379538ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 7/10 HashState ESC[1m}ESC[0mESC[2m:ESC[0m UNWINDING from 14069241
ESC[2m2022-01-25T14:27:28.379587ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 7/10 HashState ESC[1m}ESC[0mESC[2m:ESC[0m Unwinding hashed accounts
ESC[2m2022-01-25T14:27:28.955709ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 7/10 HashState ESC[1m}ESC[0mESC[2m:ESC[0m Unwinding hashed storage
ESC[2m2022-01-25T14:27:29.639839ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 7/10 HashState ESC[1m}ESC[0mESC[2m:ESC[0m DONE @ 14069240
ESC[2m2022-01-25T14:27:29.639880ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 6/10 Execution ESC[1m}ESC[0mESC[2m:ESC[0m UNWINDING from 14069241
ESC[2m2022-01-25T14:27:29.639889ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 6/10 Execution ESC[1m}ESC[0mESC[2m:ESC[0m Unwinding accounts
ESC[2m2022-01-25T14:27:30.122223ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 6/10 Execution ESC[1m}ESC[0mESC[2m:ESC[0m Unwinding storage
ESC[2m2022-01-25T14:27:30.760650ZESC[0m ESC[32m INFOESC[0m ESC[1mESC[0mESC[1m{ESC[0m Unwinding 6/10 Execution ESC[1m}ESC[0mESC[2m:ESC[0m Unwinding logs
Error: Not enough data to fill buffer
nohup: ignoring input

**Comment by vorot93** [comment] 2022-02-01 03:40
Cannot reproduce, this was probably fixed in https://github.com/akula-bft/akula/commit/5ee890d56a13c641e4787f297102a90428e5e476. Please do a fresh sync.

**Closed by vorot93** 2022-02-01 03:40 UTC
Labels: bug, P4-critical
